sonar.projectKey=Waelyacoub11_stagee_backendd
sonar.organization=waelyacoub11

# Ce chemin est relatif au fichier sonar-project.properties
sonar.sources=.
sonar.exclusions=node_modules/**,dist/**,coverage/**

# Encodage du code source
sonar.sourceEncoding=UTF-8

# Paramètres spécifiques à JavaScript/Node.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
