sonar.projectKey=Waelyacoub11_stagee_TechnoMstr
sonar.organization=Waelyacoub11

# Ce chemin est relatif au fichier sonar-project.properties
sonar.sources=src
sonar.exclusions=node_modules/**,dist/**,coverage/**,public/**

# Encodage du code source
sonar.sourceEncoding=UTF-8

# Paramètres spécifiques à Vue.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
